version: '2'
services:

  redis:
    image: redis
    networks:
      - back-end

  db:
    image: postgres:9.4
    networks:
      - back-end

  vote:
    # image: voting-app
    build: ./vote
    ports:
      - 5000:80
    networks:
      - front-end
      - back-end

  result:
    # image: result-app
    build: ./result
    ports:
      - 5001:80
    networks:
      - front-end
      - back-end

  worker:
    # image: worker
    build: ./worker
    networks:
      - back-end