redis:
  image: redis

db:
  image: postgres:9.4

vote:
  # image: voting-app
  build: ./vote
  ports:
    - 5000:80
  links:
    - redis

result:
  # image: result-app
  build: ./result
  ports:
    - 5001:80
  links:
    - db

worker:
  # image: worker
  build: ./worker
  links:
    - redis
    - db